name: 🏗️ Epic
description: High-level feature or architectural component
title: "Epic: [Domain] - [Goal]"
labels: [ "type:epic" ]
assignees: [ ]

body:
  - type: markdown
    attributes:
      value: |
        ## Epic Template
        Use this for large features that span multiple tasks (2+ weeks of work).

  - type: input
    id: domain
    attributes:
      label: Domain
      description: Which domain does this epic belong to?
      placeholder: "e.g., Plant Management, Request Management, Timeline, Admin"
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What is the high-level goal of this epic?
      placeholder: "Describe the overall objective and value this epic provides"
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What needs to be completed for this epic to be done?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: user_stories
    attributes:
      label: User Stories (Optional)
      description: Who benefits and how?
      placeholder: |
        - As a [user type], I want [functionality] so that [benefit]
        - As a [user type], I want [functionality] so that [benefit]

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this epic?
      options:
        - Critical (Blocking)
        - High (Important for MVP)
        - Medium (Nice to have)
        - Low (Future enhancement)
    validations:
      required: true

  - type: input
    id: estimate
    attributes:
      label: Estimated Duration
      description: How long do you estimate this epic will take?
      placeholder: "e.g., 2 weeks, 1 month"

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What other epics or external factors does this depend on?
      placeholder: "List any blocking dependencies"

  - type: textarea
    id: tasks
    attributes:
      label: Related Tasks
      description: List of tasks that will be created for this epic
      placeholder: |
        Will be updated as tasks are created:
        - [ ] #[number] Task: [description]
        - [ ] #[number] Task: [description]
