name: 🐛 Bug Report
description: Report a problem or unexpected behavior
title: "Bug: [Component] - [Problem Summary]"
labels: [ "type:bug" ]
assignees: [ ]

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report Template
        Use this to report problems, errors, or unexpected behavior.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: "Clear description of the problem"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: How can someone else reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "Describe what you expected to happen"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Describe what actually happened"
    validations:
      required: true

  - type: textarea
    id: error_messages
    attributes:
      label: Error Messages
      description: Any error messages or logs?
      placeholder: |
        ```
        Paste error messages, stack traces, or relevant logs here
        ```

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable)
        - High (Major functionality broken)
        - Medium (Minor functionality issues)
        - Low (Cosmetic or edge case)
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: What environment did this occur in?
      placeholder: "e.g., Local development, PHP 8.4, Laravel 12"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: "Screenshots, related issues, potential solutions, etc."
