name: ✨ Enhancement
description: Suggest an improvement or new feature
title: "Enhancement: [Feature] - [Improvement]"
labels: [ "type:enhancement" ]
assignees: [ ]

body:
  - type: markdown
    attributes:
      value: |
        ## Enhancement Template
        Use this to suggest improvements or new features.

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: What enhancement would you like to see?
      placeholder: "Clear description of the proposed feature or improvement"
    validations:
      required: true

  - type: textarea
    id: problem_solution
    attributes:
      label: Problem & Solution
      description: What problem does this solve and how?
      placeholder: |
        **Problem:** Describe the problem or limitation
        **Solution:** How would this enhancement solve it?
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Who would benefit and how?
      placeholder: "As a [user type], I want [functionality] so that [benefit]"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this enhancement?
      options:
        - High (Important for user experience)
        - Medium (Nice improvement)
        - Low (Future consideration)
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How would we know this is implemented correctly?
      placeholder: |
        - [ ] Specific criteria for completion
        - [ ] Measurable outcomes
        - [ ] User experience goals

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered other approaches?
      placeholder: "Other ways this could be implemented or achieved"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: "Screenshots, mockups, references to similar features, etc."
